default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: "nori123"  # Reemplaza con la contraseña de tu usuario PostgreSQL
  host: localhost  # O la IP de tu servidor PostgreSQL si está en otro equipo

development:
  <<: *default
  database: proyecto_ruby_2023_development

test:
  <<: *default
  database: proyecto_ruby_2023_test

production:
  <<: *default
  database: proyecto_ruby_2023_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>  # Usa variables de entorno en producción
